### ISSUE TITLE
Make it work on stable Rust

### ISSUE THREAD

**Issue by m-ou-se** [NuxiNL/argdata-rust#1]
(As requested in https://github.com/NuxiNL/cloudabi/issues/8)

**Comment by m-ou-se** [comment]
Done!

**Comment by m-ou-se** [comment]
The crate now ships its own very minimal version of `TryFrom`. You can still enable the `nightly` feature to make it use `std::convert::TryFrom` instead.

As soon as `TryFrom` becomes stable, I'll revert this change.

The other change I had to make was to stop using the `i128` feature of `ByteOrder`. Even though i128 has been stable for a while, enabling it in the `ByteOrder` crate is not possible on stable, as they try to be compatible with older versions of Rust.

**Comment by m-ou-se** [comment]
> The other change I had to make was to stop using the i128 feature of ByteOrder. Even though i128 has been stable for a while, enabling it in the ByteOrder crate is not possible on stable, as they try to be compatible with older versions of Rust.

Oops, this is no longer true. I just had to update the ByteOrder dependency. I've reverted this part.

**Comment by mcandre** [comment]
Awesome! Can we look forward to Rust stable support in cloudabi crate v0.0.4?

**Comment by m-ou-se** [comment]
The `cloudabi` crate does not depend on the `argdata` crate. 0.0.3 should already be usable on stable.

**Comment by m-ou-se** [comment]
The `set_stdio` feature used in the example is not stable though, so you won't be able to use stderr or stdout (`println!`, `eprintln!`, etc.).
